# Generated by Django 4.2 on 2023-04-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FootballCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('program', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('nationalteam', models.CharField(max_length=100)),
                ('league', models.CharField(max_length=100)),
                ('image', models.ImageField(default='images/None/no-img.jpg', upload_to='images/')),
            ],
        ),
    ]
