# Generated by Django 4.2.1 on 2023-05-12 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Collection',
        ),
    ]
