# Generated by Django 4.2.1 on 2023-05-13 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_usercollection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercollection',
            name='card',
        ),
    ]
