# Generated by Django 4.2.1 on 2023-05-13 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_usercollection_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercollection',
            name='cards',
            field=models.ManyToManyField(related_name='collections', to='myapp.footballcard'),
        ),
    ]
