# Generated by Django 4.2.1 on 2023-05-13 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_usercollection_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercollection',
            name='cards',
            field=models.ManyToManyField(blank=True, null=True, related_name='collections', to='myapp.footballcard'),
        ),
    ]
