# Generated by Django 4.2.1 on 2023-05-13 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_usercollection_cards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercollection',
            name='cards',
        ),
        migrations.CreateModel(
            name='UserCollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.footballcard')),
                ('user_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.usercollection')),
            ],
        ),
    ]
