# Generated by Django 4.1.9 on 2023-05-21 16:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_footballcard_created_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('program', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('nationalteam', models.CharField(max_length=100)),
                ('league', models.CharField(max_length=100)),
                ('image', models.ImageField(default='images/None/no-img.jpg', upload_to='images/')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_accepted', models.BooleanField(default=False)),
            ],
        ),
    ]
